### Get a user
GET http://localhost:1323/users/1
Accept: application/json

###
POST http://localhost:1323/users
Content-Type: application/json

{
  "id": "1",
  "name": "Jon Doe",
  "email": "jon.doe@email.org"
}

###Delete User
DELETE http://localhost:1323/users/1